name: Google Play Console Reviews Cookie Update

on:
  schedule:
    - cron: '0 0 */3 * *'  # Runs every 3 days at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

     # - name: Set up Chrome for Headless Execution
     #   run: |
     #     sudo apt-get update
     #     sudo apt-get install -y xvfb google-chrome-stable

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-
          
      - name: Get env Data
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "DB_PASSWORD: $DB_PASSWORD"

      - name: Run Selenium Tests (Google Play Console)
        run: mvn exec:java -Dexec.mainClass="org.example.SecureEnvExample"
#        env:
         # EMAIL: ${{ secrets.GOOGLE_EMAIL }}
#          DB_PASSWORD: "Test@123"

      - name: Notify on Failure
        if: failure()
        run: echo "Test Failed! Check logs."
